feat: 특성화 마이스터고 출신 신입 .NET 개발자가 비브로스에서 일하는 방법
boostbrothers/boostbrothers.github.io pull request #8
Opened 2021-09-06 04:26 UTC by KyungHoon0126

특성화 마이스터고 출신 신입 .NET 개발자가 비브로스에서 일하는 방법 포스트 추가

2021-09-13 01:59 UTC, mjhuh263 requested changes
고생하셨습니다!

2021-09-13 01:59 UTC, mjhuh263 commented on _draft/2021-09-06-마이스터고-출신-신입-.NET-개발자가-비브로스에서-일하는-방법.md
> +
잘 읽었습니다 경훈님! 고생많으셨습니다~ 😁
위에 간단한 목차를 추가하시면 어떨까요? 
윤호님께서 작성하신 `typescript source file을 문서화하기 ` 목차 참고하셔서 한번 작성해보시면 좋을 것 같아요!

2021-09-13 01:59 UTC, mjhuh263 commented on _draft/2021-09-06-마이스터고-출신-신입-.NET-개발자가-비브로스에서-일하는-방법.md
> +
```
1. 비브로스 합류 전 
1.1. 입사 이전에 너는 뭘했는데?
1.2. ....
2. 비브로스 합류 후 
2.1. 비브로스 신규입사자 과제 
2.2 ...
3.  앞으로의 계획 및 포부
```
이렇게 그룹핑하시면 좋을 것 같아요 ㅎㅎ

2021-09-13 01:59 UTC, mjhuh263 commented on _draft/2021-09-06-마이스터고-출신-신입-.NET-개발자가-비브로스에서-일하는-방법.md
> +과제 3가지는 추후 맡을 실무와도 연관이 있는 주제로 진행되었습니다. 매번 과제를 할 때마다 코드 리뷰를 통해 놓쳤던 부분이나 더 효율적으로 개선할 수 있는 것들에 대한 피드백을 토대로 성능을 올릴 수 있어서 많이 배울 수 있었던 것 같습니다.
받으셨던 리뷰 중 가장 기억에 남는 리뷰 하나 작성하셔도 좋을 것 같아요~
또는 피드백, 리뷰를 통한 어떤 인사이트?도 좋을 것 같습니다!

2021-09-13 01:59 UTC, mjhuh263 commented on _draft/2021-09-06-마이스터고-출신-신입-.NET-개발자가-비브로스에서-일하는-방법.md
> +토이 프로젝트를 진행하면서 정말 빠르게 일주일이 지나간 것 같습니다. 처음에는 과연 기간 안에 다 만들 수 있을까라는 걱정부터 앞섰지만 꼼꼼하게 계획을 세우고 기능을 하나하나 만들어 가다 보니 완성을 할 수 있었습니다. 그 과정에서 시행착오도 있었지만 무사히 개발을 끝낼 수 있었습니다. 아쉬운 점이 있다면 디자인이 따로 없어 UI/UX 측면에서 아쉬움이
여기도 겪으셨던 시행착오에 대해 조금 더 이야기를 풀어보시면 어떨까요? :)

2021-09-13 01:59 UTC, mjhuh263 commented on _draft/2021-09-06-마이스터고-출신-신입-.NET-개발자가-비브로스에서-일하는-방법.md
> +앞으로 비브로스에서 신규 입사자로서 막내로서 파이팅 넘치는 패기를 보여드릴 수는 없지만(?) 오늘보다 내일이 기대되는 모습을 보여드리겠습니다. 아직 많이 부족하고 사회 초년생인 저는 배울 점이 더 많지만 좋은 팀원분들 옆에서 제 몫을 다 할  수 있는 개발자로 성장하기 위해 노력하겠습니다. 감사합니다 😋
왜 보여드릴 수 없나요! ㅋㅋㅋ

2021-09-16 05:34 UTC, KyungHoon0126 commented on _draft/2021-09-06-마이스터고-출신-신입-.NET-개발자가-비브로스에서-일하는-방법.md
> +
목차 추가했습니다!

2021-09-16 05:35 UTC, KyungHoon0126 commented on _draft/2021-09-06-마이스터고-출신-신입-.NET-개발자가-비브로스에서-일하는-방법.md
> +과제 3가지는 추후 맡을 실무와도 연관이 있는 주제로 진행되었습니다. 매번 과제를 할 때마다 코드 리뷰를 통해 놓쳤던 부분이나 더 효율적으로 개선할 수 있는 것들에 대한 피드백을 토대로 성능을 올릴 수 있어서 많이 배울 수 있었던 것 같습니다.
기억에 남는 코드 리뷰 내용 추가하였습니다!

2021-09-16 05:36 UTC, KyungHoon0126 commented on _draft/2021-09-06-마이스터고-출신-신입-.NET-개발자가-비브로스에서-일하는-방법.md
> +토이 프로젝트를 진행하면서 정말 빠르게 일주일이 지나간 것 같습니다. 처음에는 과연 기간 안에 다 만들 수 있을까라는 걱정부터 앞섰지만 꼼꼼하게 계획을 세우고 기능을 하나하나 만들어 가다 보니 완성을 할 수 있었습니다. 그 과정에서 시행착오도 있었지만 무사히 개발을 끝낼 수 있었습니다. 아쉬운 점이 있다면 디자인이 따로 없어 UI/UX 측면에서 아쉬움이
겪었던 시행착오를 요약해서 추가했습니다!

2021-09-16 07:15 UTC, mjhuh263 approved these changes

2021-09-16 07:16 UTC, mjhuh263 commented
팀장님께서 최종 체크하신 후 merge 하겠습니다 :) 고생하셨습니다

2021-09-16 07:31 UTC, KyungHoon0126 commented
> 팀장님께서 최종 체크하신 후 merge 하겠습니다 :) 고생하셨습니다

피드백 해주셔서 감사합니다!

2021-09-30 04:52 UTC, lazyker commented
크으 잘썻네요.!!

2021-09-30 04:52 UTC, merged